baseURL = 'http://hostalskyview.com/'
languageCode = 'en-us'
title = 'Sky View'
defaultContentLanguage = 'es'
paginate = 20
canonifyUrls = true

[params]
    defaultDescription = ""
    defaultKeywords = ["Hostal", "Bar", "Sky View", "Room", "Rent Room", "Habitación", "Renta", "Descanso"]
    author = "Pedro Victor Navarrete Alejo"
    info = ""
    
    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = true

    address = "120, Calle Borrell, entre calle Santo Domingo y calle San Procopio, Trinidad 62600"
    phone = "(+53 5) 359-2372"
    email = "hostalskyview@gmail.com"

    formsubmit_action = "https://formsubmit.co/hostalskyview@gmail.com"

# Social links
[[params.social]]
    name = "Facebook"
    icon = "fab fa-facebook"
    weight = 1
    url = "https://www.facebook.com/profile.php?id=61555910130082"
[[params.social]]
    name = "Instagram"
    icon = "fab fa-instagram"
    weight = 2
    url = "https://www.instagram.com/skyview2421/"
[[params.social]]
    name = "Gmail"
    icon = "fa fa-envelope"
    weight = 3
    url = "mailto:hostlskyview@gmail.com"
[[params.social]]
    name = "TripAdvisor"
    icon = "fab fa-tripadvisor"
    weight = 4
    url = "https://www.tripadvisor.com/Hotel_Review-g285731-d12176965-Reviews-Hostal_Sky_View_TRINIDAD-Trinidad_Sancti_Spiritus_Province_Cuba.html?m=19905"

# Menu links
[[menu.main]]
    name = "Home"
    weight = 1
    url  = "/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
[[menu.main]]
    name = "Services"
    weight = 3
    url = "/services/"
[[menu.main]]
    name = "Rooms"
    weight = 4
    url = "/rooms/"
[[menu.main]]
    name = "Booking"
    weight = 5
    url = "/booking/"
[[menu.main]]
    name = "contactUs"
    weight = 6
    url = "/contact/"
