baseURL = 'http://hostalskyview.com/'
languageCode = 'en-us'
title = 'Sky View'
defaultContentLanguage = 'es'

[params]
    defaultDescription = ""
    defaultKeywords = ["Hostal", "Bar", "Sky View", "Room", "Rent Room", "Habitación", "Renta", "Descanso"]
    